### ISSUE TITLE
[BUG] Ncmpcpp duplicates tags.

### ISSUE THREAD

**Issue by TriaSirax** [arybczak/ncmpcpp#371] opened 2020-01-11 12:12 UTC
When I try to delete or edit a tag in tag editor, it won't overwrite the tag. Instead it appends whatever I typed to the existing tag with pipe "|" symbol in between. When I tried to delete a tag completely
 it appends itself this time. It doesn't matter which tag I edit. Even though I edit only one tag this weird bug happens to all of them. Now my tags  look like this:
1979 | 1979 | 1979 | 1979
Highway to Hell | Highway to Hell | Highway to Hell | Highway to Hell
AC/DC | AC/DC | AC/DC | AC/DC
.
.
.

When I try to get information through mpc everything seems fine. So the bug is caused by ncmpcpp.

**Comment by wylfen** [comment] 2020-01-11 12:59
I am running into this as well, and investigated more thoroughly today.

First of all, this will not happen on distributions/platforms that use the last stable release taglib-1.11.1. For me on Gentoo, the latest packaged version is taglib at https://github.com/taglib/taglib/commit/54508df30bc888c4d2359576ceb0cc8f2fa8dbdf.

The issue is how taglib's removeField method works differently, introduced in https://github.com/taglib/taglib/commit/c05fa78406fd8ce7382a11c1f63a17c4bfbe83fa#diff-b48915d5a31d8a598dc1f3e92810bbd1L189. 

There, `value` was changed from defaulting to `String:null` to `String()`, meaning that the default is now an empty string and not a null value. This means that `removeField(type)` will now attempt to remove a tag matching the empty string.

As discussed on taglib's side in https://github.com/taglib/taglib/issues/651 this should possibly not have happened. Note here that `removeField` has been marked as deprecated since at least 2015, and ncmpcpp probably should not have been using it.

The correct method to use now is `removeFields(type)`. It would also be possible to simply pass `true` instead of `false` with `tag->addField(type, *it, false);`.

I currently do not have the time to open a pull request, but will do so later today if it's not been fixed by then.

**Comment by TriaSirax** [comment] 2020-01-11 13:41
Thank you for your detailed answer. I'm also on gentoo (a newbie though). And I was not having this issue a month or two ago. Now I checked and dates are matching, they dropped 1.11.1_p20181028 and moved to 1.11p20190920-r1. So for now I'll go back to previous version. Thank you.

**Closed** 2020-01-12 11:35 UTC

**Comment by wimstefan** [comment] 2020-04-07 14:56
I'm afraid that isn't fixed yet :(
I'm also on Gentoo and use the following versions:
```
ncmpcpp 0.9_dev

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - visualizer
 - clock

encoding detection: enabled
built with support for: fftw ncurses taglib
```
```
taglib-config --version                                                                                                                                                                                               
1.11.2
```
which is media-libs/taglib-1.11.1_p20190920-r1 under Gentoo.

Please let me know if you need more information to fix that. I would be more than happy to help if that issue could be fixed!

**Comment by wylfen** [comment] 2020-04-24 16:30
I have been using ncmpcpp 0.8.2 with my patch in /etc/portage/patches ever since this issue was closed and have not run into any more problems. I also compiled ncmpcpp from current HEAD and cannot reproduce the issue.

Which ncmpcpp version are you using exactly? Are you absolutely certain it contains the fix?
