### ISSUE TITLE
ncmpcpp doesn't compile on MasOS Sierra Version 10.12.4

### ISSUE THREAD

**Issue by uladar** [arybczak/ncmpcpp#206] opened 2017-04-06 22:06 UTC
![screen shot 2017-04-07 at 12 59 31 am](https://cloud.githubusercontent.com/assets/211322/24777501/546b5900-1b2e-11e7-863e-514f247f9d7e.png)

**Comment by arybczak** [comment] 2017-04-06 22:29
What version of boost do you have? You need newer one.

**Comment by arybczak** [comment] 2017-04-06 22:30
It looks like a regression in boost 1.59 - https://svn.boost.org/trac/boost/ticket/11570.

**Comment by arybczak** [comment] 2017-04-06 22:34
Fixed in 890eaf61c75a290f1b90b0ac9077c0ba6d74ccb5.

**Closed by arybczak** 2017-04-06 22:34 UTC

**Comment by uladar** [comment] 2017-04-07 08:51
You are right. Boost version is 1.59.0
