### ISSUE TITLE
Fetch lyrics from filename heuristics if song lacks artist and title tags

### ISSUE THREAD

**Issue by liquiddandruff** [arybczak/ncmpcpp#124] opened 2016-04-11 11:28 UTC
A good amount of my songs don't have artist/title metadata set but are named like this: `{Artist/AlbumArtist} - {Title}`

When fetching lyrics on these songs, it would be nice to not need to edit the tags and just try searching for lyrics based on a simple heuristics like above (maybe make it configurable too?).

Thanks!

**Comment by arybczak** [comment] 2016-11-20 18:23
Duplicate of #72. Also, solved on master.

**Closed by arybczak** 2016-11-20 18:23 UTC
