### ISSUE TITLE
[Request] Do not split a single album according to date

### ISSUE THREAD

**Issue by easysid** [arybczak/ncmpcpp#42] opened 2015-06-02 08:41 UTC
The media library in ncmpcpp prefixes year in front of albums. This creates a problem with compilation albums that contain songs from different years. In such a case, the album is split according to year.

[This image](http://i.imgur.com/3JL9jYr.png) explains it better (ncmpcpp 0.5.10, on the left, is much cleaner). The _media_library_display_date_ options is no longer available in v0.6, which leads to this behaviour.

Is there any workaround for this?

Thanks.

**Comment by untitaker** [comment] 2015-07-22 11:54
:+1: I'm encountering this too.

**Comment by DonnieP** [comment] 2015-10-30 15:44
Yes, please give us back the media_library_display_date option.  What makes the current situation so much worse is that the media library doesn't just display a 4-digit year (which I could live with), it displays a 20-digit date/time that takes up way too much space in a 3-column media library page and forces me to maximize terminal to actually see the album title -- but I don't normally want my terminal maximized.

**Comment by livingBEEF** [comment] 2016-01-05 22:48
I second this. Having the _album_ column split one album into several albums could IMO be even classified as a bug. I don't see how that could be the intended behaviour.

**Comment by livingBEEF** [comment] 2016-01-06 16:34
Here's a workaround of sorts, for anyone who might be interested: http://pastebin.com/k4GBugsK ... seems to do the trick... probably not bug-free though.

**Comment by easysid** [comment] 2016-01-07 08:50
@livingBEEF 
I use a similar workaround [here](https://github.com/easysid/ncmpcpp), by commenting out the lines. The fork is routinely synced with upstream. It seems to work fine, but you lose all things to do with date.

**Comment by arybczak** [comment] 2016-01-16 17:30
A solution is coming.

**Comment by easysid** [comment] 2016-11-25 08:01
Is there any update to this request?

**Comment by arybczak** [comment] 2017-03-29 18:39
Fixed by 6f1e2d75160db39e7998204273230e156e223361

**Closed by arybczak** 2017-03-29 18:39 UTC

**Comment by varyoo** [comment] 2017-07-24 20:07
Maybe display the earliest date (or lastest) instead of none when `media_library_albums_split_by_date = no`?
