### ISSUE TITLE
taglib error when installing

### ISSUE THREAD

**Issue by jostber** [arybczak/ncmpcpp#83] opened 2015-11-13 04:06 UTC
I have taglib v. 1.8 installed, and I get this error when installing the recent git version:

tags.cpp: In function ‘bool Tags::write(MPD::MutableSong&)’:
tags.cpp:298:65: error: no matching function for call to
‘TagLib::MPEG::File::save(TagLib::MPEG::File::TagTypes, bool, int, bool)’
if (!mpeg_file->save(TagLib::MPEG::File::ID3v2, true, 4, false))
^
tags.cpp:298:65: note: candidates are:
In file included from tags.cpp:30:0:
/usr/include/taglib/mpegfile.h:173:20: note: virtual bool
TagLib::MPEG::File::save()
virtual bool save();
^
/usr/include/taglib/mpegfile.h:173:20: note:   candidate expects 0
arguments, 4 provided
/usr/include/taglib/mpegfile.h:184:12: note: bool
TagLib::MPEG::File::save(int)
bool save(int tags);
^
/usr/include/taglib/mpegfile.h:184:12: note:   candidate expects 1 argument,
4 provided
/usr/include/taglib/mpegfile.h:196:12: note: bool
TagLib::MPEG::File::save(int, bool)
bool save(int tags, bool stripOthers);
^
/usr/include/taglib/mpegfile.h:196:12: note:   candidate expects 2
arguments, 4 provided
/usr/include/taglib/mpegfile.h:211:12: note: bool
TagLib::MPEG::File::save(int, bool, int)
bool save(int tags, bool stripOthers, int id3v2Version);
^
/usr/include/taglib/mpegfile.h:211:12: note:   candidate expects 3
arguments, 4 provided
make[2]: **\* [tags.o] Error 1
make[2]: Leaving directory `/home/jostein/dw/ncmpcpp/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/jostein/dw/ncmpcpp'

**Comment by jostber** [comment] 2015-11-13 06:56
I get this error after testing with taglib v.1.10:

g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/taglib  -g -O2 -std=c++0x -MT window.o -MD -MP -MF .deps/window.Tpo -c -o window.o window.cpp                                                                                                        mv -f .deps/window.Tpo .deps/window.Po                                                                                                                                                                                                             /bin/sh ../libtool --tag=CXX   --mode=link g++  -g -O2 -std=c++0x   -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata   -lboost_thread -lmpdclient   -lreadline -ltermcap -lpthread -L/usr/lib64 -lncursesw -lfftw3 -lm   -lcurl -L/usr/lib -ltag                                                                 libtool: link: g++ -g -O2 -std=c++0x -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread /usr/lib64/libmpdclient.so -lreadline -ltermcap -lpthread -L/usr/lib64 -lncursesw /usr/lib64/libfftw3.so -lm /usr/lib64/libcurl.so /usr/lib64/libidn.so /usr/lib64/libldap.so /usr/lib64/liblber.so /usr/lib64/libsasl2.so -ldl -lresolv -lssl -lcrypto -lz -L/usr/lib -ltag                                                                                                                                                                                   tags.o: In function `Tags::write(MPD::MutableSong&)':                                                                                                                                                                                              /home/jostein/dw/ncmpcpp/src/tags.cpp:298: undefined reference to `TagLib::MPEG::File::save(int, bool, int, bool)'                                                                                                                                 collect2: error: ld returned 1 exit status                                                                                                                                                                                                         make[2]: *** [ncmpcpp] Error 1                                                                                                                                                                                                                     make[2]: Leaving directory `/home/jostein/dw/ncmpcpp/src'                                                                                                                                                                                          make[1]: *** [all-recursive] Error 1                                                                                                                                                                                                               make[1]: Leaving directory `/home/jostein/dw/ncmpcpp'                                                                                                                                                                                              make: *** [all] Error 2

**Comment by arybczak** [comment] 2015-11-13 15:43
For some reason tags.o is put after all the linker flags, that's the cause. I'm not sure why this happens, but if you execute this command by hand and put tags.o before all the -l* stuff, it should work.

**Comment by arybczak** [comment] 2015-11-13 15:44
Also, what version is this?

**Comment by jostber** [comment] 2015-11-13 17:40
On 13.11.15,07:44, Andrzej Rybczak wrote:
> Also, what version is this?
> 

First taglib v.1.8 then v.1.10
Slackware 14.1
ncmpcpp git


Jostein

**Comment by arybczak** [comment] 2015-11-13 21:56
It should work with 1.9.1. I can't test with taglib 1.10 now, sorry.

**Comment by arybczak** [comment] 2015-11-15 16:23
Checked with 1.10 and it works fine for me.

**Comment by arybczak** [comment] 2016-11-23 20:00
This should be fixed.

**Closed by arybczak** 2016-11-23 20:00 UTC
